### ISSUE TITLE
`/api/v2/records/:uuid` is generating a massive number of data series in Prometheus

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow-efolder#987]
The root cause is https://github.com/department-of-veterans-affairs/appeals-deployment/pull/1377. Since this feature was turned on, Prometheus has been crashing. At its peak, we observed over 250k series per `/metrics` API call. Since Prometheus polls `/metrics` every 15s, it was not able handle the load.

To fix this, we need to implement a label collapser in eX similar to one in Caseflow.
https://github.com/department-of-veterans-affairs/caseflow/blob/master/config.ru#L25

Here's a sample `/metric` output from efolder server.
```
http_server_request_duration_seconds_bucket{code="200",method="options",host="efolder.cf.ds.va.gov",path="/api/v2/records/7D11AE16-1DFF-49F5-AE31-B9E4675EBC30",le="0.005"} 1.0
http_server_request_duration_seconds_bucket{code="200",method="options",host="efolder.cf.ds.va.gov",path="/api/v2/records/7D11AE16-1DFF-49F5-AE31-B9E4675EBC30",le="0.01"} 1.0
http_server_request_duration_seconds_bucket{code="200",method="options",host="efolder.cf.ds.va.gov",path="/api/v2/records/7D11AE16-1DFF-49F5-AE31-B9E4675EBC30",le="0.025"} 1.0
http_server_request_duration_seconds_bucket{code="200",method="options",host="efolder.cf.ds.va.gov",path="/api/v2/records/7D11AE16-1DFF-49F5-AE31-B9E4675EBC30",le="0.05"} 1.0
http_server_request_duration_seconds_bucket{code="200",method="options",host="efolder.cf.ds.va.gov",path="/api/v2/records/7D11AE16-1DFF-49F5-AE31-B9E4675EBC30",le="0.1"} 1.0
http_server_request_duration_seconds_bucket{code="200",method="options",host="efolder.cf.ds.va.gov",path="/api/v2/records/7D11AE16-1DFF-49F5-AE31-B9E4675EBC30",le="0.25"} 1.0
http_server_request_duration_seconds_bucket{code="200",method="options",host="efolder.cf.ds.va.gov",path="/api/v2/records/7D11AE16-1DFF-49F5-AE31-B9E4675EBC30",le="0.5"} 1.0
http_server_request_duration_seconds_bucket{code="200",method="options",host="efolder.cf.ds.va.gov",path="/api/v2/records/7D11AE16-1DFF-49F5-AE31-B9E4675EBC30",le="1"} 1.0
http_server_request_duration_seconds_bucket{code="200",method="options",host="efolder.cf.ds.va.gov",path="/api/v2/records/7D11AE16-1DFF-49F5-AE31-B9E4675EBC30",le="2.5"} 1.0
http_server_request_duration_seconds_bucket{code="200",method="options",host="efolder.cf.ds.va.gov",path="/api/v2/records/7D11AE16-1DFF-49F5-AE31-B9E4675EBC30",le="5"} 1.0
http_server_request_duration_seconds_bucket{code="200",method="options",host="efolder.cf.ds.va.gov",path="/api/v2/records/7D11AE16-1DFF-49F5-AE31-B9E4675EBC30",le="10"} 1.0
http_server_request_duration_seconds_bucket{code="200",method="options",host="efolder.cf.ds.va.gov",path="/api/v2/records/7D11AE16-1DFF-49F5-AE31-B9E4675EBC30",le="+Inf"} 1.0
```

To overcome this, I hacked the `/etc/prometheus/prometheus.yml` file to skip over all efolder servers.

```yml
  - job_name: 'rails-metrics'
    ec2_sd_configs:
      - region: us-gov-west-1
        port: 3000
    relabel_configs:
        - source_labels: [__meta_ec2_tag_deploy_env]
          regex: prod
          action: keep
        - source_labels: [__meta_ec2_instance_id]
          target_label: instance
        - source_labels: [__meta_ec2_tag_app_name]
          target_label: appname
        - source_labels: [__meta_ec2_tag_app_name]   <- drop action on all efolder servers
          regex: efolder
          action: drop
        - source_labels: [__meta_ec2_tag_deploy_env]
          target_label: env
        - source_labels: [__meta_ec2_tag_type]
          regex: utility
          action: drop
```

@lisac-usds 
@RobertAlexanderUSDS 
@sunil-sadasivan 
@lowellrex 
@mdbenjam
